### PR TITLE
Bump pyfakefs to support Python 3.12

### PR DESCRIPTION
**Pull request by dimaqq**
Older `pyfakefs` fails with:

```
    flavour = pathlib._Flavour  # type: ignore [attr-defined]
              ^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_Flavour'
```

### CODE REVIEW

**Comment by dimaqq** [comment]
poke @ojii

**Review by ojii — APPROVED** [review]

**Comment by dimaqq** [comment]
I can't merge this PR until GHA completes and GHA won't run until maintainer approves running the workflow on the PR 🙇🏻

**Comment by y26805** [comment]
> I can't merge this PR until GHA completes and GHA won't run until maintainer approves running the workflow on the PR 🙇🏻

approved the run! looks mergeable now 🙏

**Comment by dimaqq** [comment]
let me fix typing complaints and hopefully it will be all good.

P.S. 
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by dimaqq** [comment]
@y26805 please consider allowing GHA again 🙇🏻 and maybe merge it if all checks pass, because I'm not allowed to 🙇🏻

**Comment by y26805** [comment]
looks like all tests passed, will merge this. thanks @dimaqq 🙏

**Pull request merged**
