### PR TITLE
circleci ➡️ github actions

### PR DESCRIPTION
**Pull request by ojii**
would be nice to reduce some of the repetition but i'm just happy it works at all.

### CODE REVIEW

**Comment by ojii** [comment]
by far the slowest part of this whole ci pipeline is poetry install without a lock file. I wonder if it's possible to only run this once (or rather, run `poetry lock`) and then re-use it in subsequent steps.

**Review by dimaqq — APPROVED** [review]
Merge it, improve later!

**Comment by dimaqq** [comment]
> by far the slowest part of this whole ci pipeline is poetry install without a lock file. I wonder if it's possible to only run this once (or rather, run `poetry lock`) and then re-use it in subsequent steps.

maybe that's a good reason to check in `poetry.lock`, finally?

**Comment by ojii** [comment]
> maybe that's a good reason to check in `poetry.lock`, finally?

I still think that's a bad practice for _libraries_.

**Comment by ojii** [comment]
> Merge it, improve later!

i wanna mess in this branch a bit until it's somewhat decent and then squash the commits

**Pull request merged**
