### PR TITLE
Update maximum operations per transaction to 100

### PR DESCRIPTION
**Pull request by stupoid**
This resolves https://github.com/HENNGE/aiodynamo/issues/153 by updating the max values from 25 to 100.

### CODE REVIEW

**Comment by stupoid** [comment]
I think there might be an issue with the CI, particularly `Run poetry lock`.

**Comment by FurqanHabibi** [comment]
@stupoid Perhaps we can retry this?

**Comment by stupoid** [comment]
> @stupoid Perhaps we can retry this?

I don't seem to have the permissions to re-run this through the Github UI.

**Review by dimaqq — APPROVED** [review]

**Comment by y26805** [comment]
should we just merge this one? can't figure out how to re-run the CI either, but the changes look pretty straightforward.

**Comment by ojii** [comment]
pulled the changes into a branch on this repo to hopefully pacify github actions, will close this PR https://github.com/HENNGE/aiodynamo/pull/160

**Pull request closed without merging**
