### PR TITLE
Add transact get items method to client

### PR DESCRIPTION
**Pull request by nicolaszein**
Adding support for [TransactGetItems](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactGetItems.html)

### CODE REVIEW

**Comment by nicolaszein** [comment]
Hi @ojii, can you take a look on this? 😃

**Comment by ojii** [comment]
@nicolaszein I'm sorry for the delay, I've had a quick look at it and pretty sure it's fine, but was a bit busy with other things. Expect this to merge & release early next week.

**Comment by nicolaszein** [comment]
Hi @ojii, no worries!

Thank you for your attention

**Review by ojii — APPROVED** [review]

**Comment by ojii** [comment]
thank you for implementing this.

**Pull request merged**
